server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring?serverTimezone=Asia/Seoul
    username: spring
    password: 1234
  session:
    redis:
      repository-type: indexed
      flush-mode: immediate
  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

  profiles:
    active: local
    include: oauth

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.app.app.domain; com.app.app.dto;
  type-handlers-package: com.app.app.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true

# openssl rand -base64 32
jwt:
  secret: OK4V20ACS5A+oy+jvpZ0oFFrsur1VZO6Upjop4TRa+Y=











